name: K6 Tests - Manual - JSON

on:
  workflow_dispatch: # Permite la ejecución manual

jobs:
  k6-tests-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: |
            ./HTTP/09-script.js
